
Traffic <- read.csv(file="C:/Users/samue/Desktop/W25/CSVs/bi-traffic_w25.csv", header=TRUE, sep=",") 
Traffic_Arranged <- subset(Traffic, select = c(12,4,18,14,16,2,13,7,11,8,1,9,10,15,17)) 
Traffic_main<- read.csv(file="C:/Users/samue/Desktop/W25/CSVs/traffic_final_w24.csv", header=TRUE, sep=",") 
names(Traffic_Arranged)[11]=paste("ga.bounces")
Traffic_final <- rbind(Traffic_main, Traffic_Arranged) 
#levels(Traffic_final$ipg.subProduct) 
Traffic_final$ipg.subProduct=gsub(".*-.*", "mixed", Traffic_final$ipg.subProduct) 
Traffic_final$ga.contentGroup1=gsub(".*-.*", "mixed", Traffic_final$ga.contentGroup1)  
write.csv(Traffic_final, file = "C:/Users/samue/Desktop/W25/CSVs/traffic_final_w25.csv")                                            

Conversion <- read.csv(file="C:/Users/samue/Desktop/W25/CSVs/bi-conversions-w39.csv", header=TRUE, sep=",")  
Conversion_Arranged <- subset(Conversion, select = c(11,3,19,15,16,17,1,12,8,14,13,9,10,18)) 
 Conversion_main<- read.csv(file="C:/Users/samue/Desktop//W25/CSVs/bi-conversions_final_w24.csv", header=TRUE, sep=",") 
names(Conversion_Arranged)[7]=paste("ga.contentGroup1") 
names(Conversion_Arranged)[2]=paste("ga.date") 
Conversion_final <- rbind(Conversion_main, Conversion_Arranged) 
View(Conversion_final) 
View(Conversion_final) 
Conversion_final$ipg.subProduct=gsub(".*-.*", "mixed", Conversion_final$ipg.subProduct) 
#Conversion_final$ipg.contentGroup1=gsub(".*-.*", "mixed", Conversion_final$ipg.contentGroup1) 
write.csv(Conversion_final, file = "C:/Users/samue/Desktop/W25/CSVs/conversion_final_w25.csv")            


Conversion_unique_main<- read.csv(file="C:/Users/samue/Desktop/W25/CSVs/Conversion_unique_final_w24.csv", header=TRUE, sep=",") 
Traffic <- read.csv(file="C:/Users/samue/Desktop/W25/CSVs/bi-traffic_w25.csv", header=TRUE, sep=",") 
Conversion_unique <- subset(Traffic, select = c(12,4,18,14,15,2,13,7,6,17)) 
Conversion_unique_final <- rbind(Conversion_unique_main, Conversion_unique) 
write.csv(Conversion_unique_final, file = "C:/Users/samue/Desktop/W25/CSVs/Conversion_unique_final_w25.csv")   